#!/bin/bash
# Script to generate cover letters
# Author: Alex Wyner

today=$(date +%m/%d/%Y)
read -rp "Enter company name: " comp
read -rp "Enter file name for letter w/o file extension: " fname
read -rp "Enter hiring manager name (Leave blank for Hiring Team): " name
read -rp "Enter role: " role
read -rp "Enter company info: " comp_info
read -rp "I am excited for the potential opportunity to...: " goal

if [[ -z $name ]] 
then
    name="Hiring Team"
fi

if [[ ! -d $fname ]]
then
    mkdir $fname
fi

dir=$fname

fname="$fname.docx"
cp template.docx $fname

unzip $fname -d $dir
rm $fname
cd $dir

sed -i "s/DATE/$today/g" word/document.xml
sed -i "s/COMP/$comp/g" word/document.xml
sed -i "s/NAME/$name/g" word/document.xml
sed -i "s/ROLE/$role/g" word/document.xml
sed -i "s/INFO/$comp_info/g" word/document.xml
sed -i "s/GOAL/$goal/g" word/document.xml

zip -r ../letters/$fname *
cd ..

