#!/bin/bash

if [[ $UID != 0 ]]
then
    echo "Run as root"
    exit 1
fi

zerotier-cli listnetworks | grep db64858fed03a926 > /dev/null
status=$(echo $?)

if [[ $status -eq 0 ]]
then
    echo "VPN connected"
else
    echo "VPN disconnected"
fi

